DOCS-14043 change field to notPrimaryUnacknowledgedWrites
mongodb/docs pull request #4737
Opened 2020-12-30 19:55 UTC by davemungo

2021-01-07 21:08 UTC, andf-mongodb requested changes

2021-01-07 21:08 UTC, andf-mongodb commented on source/reference/command/serverStatus.txt
> +   be updated.
Let's go with:

> This field name was changed in MongoDB 4.4.3. Previously, this field was named `XXX`.

2021-01-08 02:30 UTC, davemungo commented on source/reference/command/serverStatus.txt
> +   be updated.
Done

2021-01-08 16:11 UTC, davemungo commented
moved to 4.4.3 https://github.com/mongodb/docs/pull/4756

2021-01-08 16:11 UTC, closed without merging