DOCSP-15489 update mongo shell banner for mongosh
mongodb/docs pull request #5280
Opened 2021-04-30 15:02 UTC by davemungo

There are a large number of files in this change set. Most of them have only superficial changes. Here is a short summary of the changes made:

The substantive changes are found in the following files: 
source/includes/fact-mongosh-shell-method.rst
source/includes/fact-mongosh-shell-method-toc.rst

Two index pages had updates:
source/reference/method/js-collection.txt
source/reference/method/js-cursor.txt

One method was only partially migrated to mongosh
source/reference/method/db.getMongo.txt

There was a small, title change in:
source/reference/method.txt

The remaining files in the change set were updated to reflect filenames for the include files. 
source/includes/fact-mongo-shell-method.rst  was renamed: 
source/includes/fact-mongosh-shell-method.rst

source/includes/fact-mongo-shell-method-toc.rst was renamed:
source/includes/fact-mongosh-shell-method-toc.rst

### STAGING LINKS ###
### This is a sample page using the updated banner
https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/DOCSP-15489-update-mongo-shell-banner-for-mongosh-v5.0/reference/method/db.collection.distinct/

### These pages use the updated index files:
https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/DOCSP-15489-update-mongo-shell-banner-for-mongosh-v5.0/reference/method/js-cursor/
https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/DOCSP-15489-update-mongo-shell-banner-for-mongosh-v5.0/reference/method/js-collection/

### This page references a method which was not ported to mongosh
https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/DOCSP-15489-update-mongo-shell-banner-for-mongosh-v5.0/reference/method/db.getMongo/

2021-04-30 15:04 UTC, davemungo commented on source/includes/fact-mongosh-shell-method-toc.rst
> +   - :v4.4:`mongo shell v4.4 </mongo>`
NB: This link is not yet live so it doesn't appear on the staging page. The link will be updated before the docs are released.

2021-04-30 15:04 UTC, davemungo commented on source/includes/fact-mongosh-shell-method.rst
> +   - :v4.4:`mongo shell v4.4 </mongo>`
NB: This link is not yet live so it doesn't appear on the staging page. The link will be updated before the docs are released.

2021-04-30 15:26 UTC, addaleax approved these changes

2021-04-30 15:30 UTC, mmarcon commented
There is a difference in `Cursor.map()` between `mongo` and `mongosh`. In `mongo`, that method returns an array. However, in `mongosh` that method returns the `Cursor` object again. If you need the array you have to call `cursor.map().toArray()`.

2021-04-30 16:43 UTC, jeff-allen-mongo requested changes

2021-04-30 16:43 UTC, jeff-allen-mongo commented on source/includes/fact-mongosh-shell-method-toc.rst
> +   - :v4.4:`mongo shell v4.4 </mongo>`
This bulleted list should not be indented like this. It will show an "unexpected indentation" error in the build log.

2021-05-03 17:37 UTC, jeff-allen-mongo approved these changes

2021-05-03 17:37 UTC, merged